templates_project/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

# Template Tagging
app_name = 'basicapp'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
]

templates_project/templates_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basicapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^basicapp/', include('basicapp.urls')),
]

templates_project/basicapp/models.py
from django.db import models

# Create your models here.

templates_project/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basicapp/index.html', context_dict)

def other(request):
    return render(request, 'basicapp/other.html')

def relative(request):
    return render(request, 'basicapp/relative_url_template.html')

templates_project/templates/basicapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:other' %}">OTHER</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>

  </body>
</html>

templates_project/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>Welcome to Index</h1>
    <h1>This is index.html page showing</h1>
    <h2>
      {{ text|cut:"hello" }}
      <br>
      {{ number|add:"99"|add:"-98" }}
    </h2>
  {% endblock %}

templates_project/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>Welcome to Other</h1>
    <h2>This is example of template inheritance</h2>
  {% endblock %}

templates_project/templates/basicapp/relative_url_template.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Rel URL</title>
  </head>
  <body>
    <h1>Welcome to Relative URL Template</h1>
    <a href="{% url 'basicapp:other' %}">The Other Page</a>
    <br>
    <a href="{% url 'admin:index' %}">Admin</a>
    <br>
    <a href="{% url 'index' %}">Go to Index</a>

  </body>
</html>